version: '3.3'

services:

  db:
    restart: always
    container_name: pg_db
    image: postgres:15.2
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    volumes:
        - ./db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
      